<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('video_prompts', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->id();
            $table->foreignId('user_id')->constrained()->cascadeOnDelete();

            // The still image this motion prompt is meant to animate.
            $table->foreignId('story_image_prompt_id')->constrained()->cascadeOnDelete();

            // Text-to-motion prompt describing how the still should be animated
            // (camera movement, subject motion, pacing) — generated by
            // VideoPromptService from the source image + its original prompt.
            $table->text('prompt');

            $table->unsignedInteger('coin_cost')->default(0);
            $table->timestamp('generated_at')->nullable();
            $table->text('last_generation_error')->nullable();
            $table->unsignedInteger('generation_attempts')->default(0);

            $table->timestamps();

            $table->index(['story_image_prompt_id', 'generated_at'], 'vp_sip_generated_idx');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('video_prompts');
    }
};
